Fixed unescaped left brace in regex to be compatible with Perl 5.30+
oasys/mkrdns pull request #4
Opened 2019-09-01 23:29 UTC by spike77453

This fixes an unescaped left brace so that mkrdns works with Perl 5.30+. This also fixes the following deprecation warning:

```
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^\}]+)}/ at /usr/bin/mkrdns line 900.
```

2021-02-11 14:31 UTC, oasys requested changes
I think this would be more readable and match the existing style as a character class:

```perl
    s@\$[{]([^}]+)}@
```

Could you update and test?

2021-02-11 20:55 UTC, spike77453 commented
Works for me. I've updated to commit accordingly.

2021-02-12 03:25 UTC, oasys commented
Thanks for the quick response.   Before merging, I took a longer look at the code and there seems to be more than this one instance of an unescaped left brace.   I'd like to address them all in this fix, if possible.

2021-02-12 15:28 UTC, oasys commented
Reading `perldiag`, I now understand why the other instances aren't being alerted.

```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/%s/
           (F) The simple rule to remember, if you want to match a literal "{" character
           (U+007B "LEFT CURLY BRACKET") in a regular expression pattern, is to escape
           each literal instance of it in some way.  Generally easiest is to precede it
           with a backslash, like "\{" or enclose it in square brackets ("[{]").  If the
           pattern delimiters are also braces, any matching right brace ("}") should also
           be escaped to avoid confusing the parser, for example,

            qr{abc\{def\}ghi}

           Forcing literal "{" characters to be escaped enables the Perl language to be
           extended in various ways in future releases.  To avoid needlessly breaking
           existing code, the restriction is not enforced in contexts where there are
           unlikely to ever be extensions that could conflict with the use there of "{" as
           a literal.  Those that are not potentially ambiguous do not warn; those that
           are do raise a non-deprecation warning.

           The contexts where no warnings or errors are raised are:

           o   as the first character in a pattern, or following "^" indicating to anchor
               the match to the beginning of a line.

           o   as the first character following a "|" indicating alternation.

           o   as the first character in a parenthesized grouping like

                /foo({bar)/
                /foo(?:{bar)/

           o   as the first character following a quantifier

                /\s*{/
```

In general, it is a good idea to escape all literal "{" characters in regexes.  I've updated all the others I found.

2021-02-12 15:35 UTC, oasys approved these changes

2021-02-12 15:36 UTC, merged